version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/code"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/automation"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - update-types: ["version-update:semver-major"]
