version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/code"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/automation"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
