#!/usr/bin/env python3
"""Update docs/superpowers/BASELINE.md with git sha, python version, pytest + sample eval (Phase 0)."""
from __future__ import annotations

import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE_MD = REPO / "docs" / "superpowers" / "BASELINE.md"
CODE = REPO / "code"


def _run(cmd: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        env={**os.environ, **(env or {})},
    )


def main() -> int:
    git_sha = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    ).stdout.strip() or "unknown"

    branch = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    ).stdout.strip() or "unknown"

    py_ver = sys.version.replace("\n", " ")

    env_off = {**os.environ, "ORCHESTRATE_DISABLE_LLM": "1"}

    pr = _run([sys.executable, "-m", "pytest", "tests", "-q"], cwd=CODE)
    pytest_ok = pr.returncode == 0
    pytest_tail = (pr.stdout + pr.stderr)[-4000:]

    er = _run(
        [sys.executable, "run_eval.py", "--offline"],
        cwd=CODE,
        env=env_off,
    )
    eval_ok = er.returncode == 0
    eval_out = er.stdout + er.stderr

    routing: dict[str, str] = {}
    for line in eval_out.splitlines():
        m = re.search(r"(status|request_type|product_area):\s+([\d.]+%)", line)
        if m:
            routing[m.group(1)] = m.group(2)

    batch = _run(
        [sys.executable, "main.py", "--limit", "0"],
        cwd=CODE,
        env=env_off,
    )
    batch_ok = batch.returncode == 0
    rows_line = ""
    for line in (batch.stderr + batch.stdout).splitlines():
        if "Wrote" in line and "rows" in line:
            rows_line = line.strip()
            break

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    body = f"""# Competitive baseline snapshot (Orchestrate)

> Auto-generated by `scripts/capture_baseline.py`. Re-run after meaningful changes to compare regressions.

## Recorded

| Field | Value |
|-------|-------|
| **UTC timestamp** | {ts} |
| **Git branch** | `{branch}` |
| **Git commit** | `{git_sha}` |
| **Python** | `{py_ver}` |

## Automated checks (offline LLM)

| Check | Result |
|-------|--------|
| `pytest tests -q` | {'PASS' if pytest_ok else 'FAIL'} |
| `run_eval.py --offline` (sample routing) | {'PASS' if eval_ok else 'FAIL'} |
| `main.py --limit 0` (full batch) | {'PASS' if batch_ok else 'FAIL'} |

### Sample routing exact match (public labels)

| Column | Exact match |
|--------|-------------|
| status | {routing.get('status', 'n/a')} |
| request_type | {routing.get('request_type', 'n/a')} |
| product_area | {routing.get('product_area', 'n/a')} |

### Full batch

{rows_line or '(no Wrote … rows line captured)'}

## pytest output (tail)

```
{pytest_tail}
```

## eval_sample output (tail)

```
{(eval_out[-3500:])}
```

## When to refresh

- Before/after retrieval, taxonomy, risk, or grounding changes.
- Before generating final `support_tickets/output.csv` for submission.

---
*Phase 0 of `docs/superpowers/plans/2026-05-02-path-to-winner.md`.*
"""
    BASELINE_MD.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_MD.write_text(body, encoding="utf-8")
    print(f"Wrote {BASELINE_MD}", file=sys.stderr)
    return 0 if pytest_ok and eval_ok and batch_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
